# Site settings
name: Leo Nguyen
title: Leo Nguyen | Intelligence Analyst
description: Rapid intelligence analyst and inbox manager
url: https://leokhoivi.github.io/
baseurl: ''
email: leokhoivi@gmail.com
cover: https://leokhoivi.github.io/img/og.png
logo: https://leokhoivi.github.io/img/emojis/technologist.png
resume: https://leokhoivi.github.io/resume.pdf
social:
  - title: email
    url: mailto:leokhoivi@gmail.com
  - title: twitter
    url: https://twitter.com/leokhoivi
  - title: github
    url: https://github.com/leokhoivi
  - title: linkedin
    url: https://www.linkedin.com/in/leokhoivi

# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
